###
POST https://qwsopzco8h.execute-api.eu-central-1.amazonaws.com/default/createEvent HTTP/1.1
Content-Type: application/json

{
    "name": "Wadde hadde dudde da?"
}

###
GET https://qwsopzco8h.execute-api.eu-central-1.amazonaws.com/default/getAllEvents HTTP/1.1